package co.idearun.learningapp.di

import co.idearun.learningapp.data.local.di.formBuilderLocalModule
import co.idearun.learningapp.data.remote.di.createRemoteFormModule
import co.idearun.learningapp.data.repository.di.formRepositoryModule
import co.idearun.learningapp.feature.di.featureModule

const val xapikey="717ed4b1fb84033653eaf6a69da4eb3be1011657"
const val secretkey="eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Im15YXBwLTAwMSJ9.eyJ0b2tlbiI6ImF1dGgiLCJzaWQiOiJiYjgxMGNjZS1iMDQyLTQ2MTgtYWFjMy04OGRjOGI3NGM4OTgiLCJ1aWQiOjgsImVtYWlsIjoiZWxoYW1mZXl6b2xhaGlAZ21haWwuY29tIiwiZmlyc3RfbmFtZSI6IkVsaGFtIiwibGFzdF9uYW1lIjoiRmV5em9sYWhpIiwicGhvbmVfbnVtYmVyIjoiIiwidXNlcm5hbWUiOiJ1c2VyX2tGeWp4dkZQSkwiLCJ2ZXJpZmllZF9lbWFpbCI6ZmFsc2UsInZlcmlmaWVkX3Bob25lIjpmYWxzZSwibGFzdF91cGRhdGUiOiIyMDIwLTA2LTIyVDA3OjU5OjUyLjkxMVoiLCJncm91cHMiOiIiLCJpc3MiOiJpY2FzIiwiYXVkIjpbImljYXMiLCJjcm0iLCJmb3JteiIsImludm9pY2UiLCJwcm9qZWN0YW50IiwiYWN0aW9ucyJdLCJleHAiOjE2MjY3NzUzOTMsImlhdCI6MTYyNDE4MzM5M30.UlIUzS_Bp4tdHyTfZ3aBAyu97xwWUYaWOkDgPKttF9jm1e68IZOvP3nc7gyQVSPOAr_cZTcVtX_K39nfsSNmmP5AgxkGbtjsQxbWzXNfiK50N1zFf_EKwrXrOc2ETdda_VTUUPYRUJHZmHKA2ydZoo2Q2v1Wyft8a0eH5HddE54"
const val baseurl="https://api.formaloo.net/"

val appComponent = listOf(
    createRemoteFormModule(baseurl,xapikey,secretkey),
    formBuilderLocalModule,
    formRepositoryModule,
    featureModule
)