package co.idearun.learningapp.di

import co.idearun.learningapp.data.local.di.formBuilderLocalModule
import co.idearun.learningapp.data.remote.di.createRemoteFormModule
import co.idearun.learningapp.data.repository.di.formRepositoryModule
import co.idearun.learningapp.feature.di.featureModule

const val xapikey="4638feb8378ac5799d6200889f97f2d3d88b9852"
const val secretkey="eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Im15YXBwLTAwMSJ9.eyJ0b2tlbiI6ImF1dGgiLCJzaWQiOiI5ZjY1Y2QyYi0wYzc1LTRhOWYtYjQ5OC0zMWJhNTZhMzQ0ZTEiLCJ1aWQiOjM0OCwiZW1haWwiOiJlbGhhbWZleXpvbGFoaUBnbWFpbC5jb20iLCJmaXJzdF9uYW1lIjoiRWxoYW0iLCJsYXN0X25hbWUiOiJGZXl6b2xhaGkiLCJwaG9uZV9udW1iZXIiOiIwOTM2NTgyNTg5IiwidXNlcm5hbWUiOiJlbGhhbWZleXpvbGFoaUBnbWFpbC5jb20iLCJ2ZXJpZmllZF9lbWFpbCI6ZmFsc2UsInZlcmlmaWVkX3Bob25lIjpmYWxzZSwibGFzdF91cGRhdGUiOiIyMDIxLTA0LTExVDA3OjE2OjMwLjQ1NFoiLCJncm91cHMiOiIiLCJpc3MiOiJpY2FzIiwiYXVkIjpbImljYXMiLCJjcm0iLCJmb3JteiIsImludm9pY2UiLCJwcm9qZWN0YW50IiwiYWN0aW9ucyJdLCJleHAiOjE2MjY3Njg2NjQsImlhdCI6MTYyNDE3NjY2NH0.DsFdPVy02lDTFoFPsTqYgKoV7cBBvCNtAAxGQLuyE5C6rq9hRjmebPlXhvylnepWu5vTy9AlcUeaJx1z1Sw2l5Mtk60ZjHPW_3VyWriNMDGde35T_Bcl49uZxnxseBGAZ5KJhdJXsg5cB5kbcVSwkv0Wo1MxzZmd-MFAJCNjr_eqB0_0gDExKxhbCbmnSqiyqkEDc_k88UtmWXMfCaN8xBh-ljhy37JPHIbrxp-k17tppcjd8Uq0VvfkNBHnxcjtHVtQ0dqShI6E916v-cfMEmlV46AZwVoOCbQR51zVVDn89I6AO6ViURv6SzsKwWB_mj9ejlub_OMZChAOX9yPGA"
const val baseurl="https://api.staging.formaloo.com/"

val appComponent = listOf(
    createRemoteFormModule(baseurl,xapikey,secretkey),
    formRepositoryModule,
    featureModule,
    formBuilderLocalModule
)